# No seu docker-compose.yml
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Desafio@123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql # Adicione esta linha

# Adicione esta seção no final do arquivo
volumes:
  sqlserver_data:
